Refactoring flume agent service and add status

diff --git a/flume/flume-1.5.2/rpm/sources/flume-agent.init b/flume/flume-1.5.2/rpm/sources/flume-agent.init
--- a/flume/flume-1.5.2/rpm/sources/flume-agent.init
+++ b/flume/flume-1.5.2/rpm/sources/flume-agent.init
@@ -40,10 +40,10 @@ fi
 
 if [ -f /etc/profile.d/java.sh ]; then
         . /etc/profile.d/java.sh
-        [ -z "\$JAVA_HOME" ] && echo "JAVA_HOME is not defined" && exit 1
+        [ -z "\$JAVA_HOME" ] && echo "JAVA_HOME is not defined" && return 1
 else
 	echo "enviroment not properly set up"
-        exit 1
+        return 1
 fi
 
 ERROR_PROGRAM_NOT_INSTALLED=5
@@ -64,28 +64,64 @@ for dir in "$FLUME_RUN_DIR" "$FLUME_LOCK_DIR"; do
 done
 
 start() {
-  [ -x $exec ] || exit $ERROR_PROGRAM_NOT_INSTALLED
-
+  [ -x $exec ] || return $ERROR_PROGRAM_NOT_INSTALLED
   getAgentNames
+  error=0
   for i in $agentNames
   do
+    /bin/su -s /bin/bash -c "${EXEC_PATH} $i status"
+    rc=$?
+    [ $rc -eq 0 ] && continue
+    [ $rc -ne 3 ] && /bin/su -s /bin/bash -c "${EXEC_PATH} $i stop"
     /bin/su -s /bin/bash -c "${EXEC_PATH} $i start"
+    ((error+=$?))
   done
-  return 0
+  [ $error -eq 0 ] && return 0 || return 1
 }
 
 stop() {
   getAgentNames
+  error=0
   for i in $agentNames
   do
+    /bin/su -s /bin/bash -c "${EXEC_PATH} $i status"
+    rc=$?
+    [ $rc -eq 3 ] && continue
     /bin/su -s /bin/bash -c "${EXEC_PATH} $i stop"
+    ((error+=$?))
   done
-  return 0
+  [ $error -eq 0 ] && return 0 || return 1
+}
+
+checkstatus() {
+  getAgentNames
+  running=0
+  stopped=0
+  error=0
+  total=0
+  for i in $agentNames
+  do
+    ((total++))
+    /bin/su -s /bin/bash -c "${EXEC_PATH} $i status"
+    rc=$?
+    if [ $rc -eq 0 ]; then
+      ((running++))
+    elif [ $rc -eq 3 ]; then
+      ((stopped++))
+    else
+      ((error++))
+    fi
+  done
+  [ $total -eq $running ] && echo "Running" && return 0
+  [ $total -eq $stopped ] && echo "Stopped" && return 3
+  echo "Error: there are $running agents, $stopped stopped and $error in error state" 
+  return 1
 }
 
 restart() {
   stop
-  start
+  [ $? -eq 0 ] && start
+  return $?
 }
 
 getAgentNames()
@@ -105,18 +141,23 @@ condrestart(){
 case "$1" in
   start)
     start
+    RETVAL=$?
     ;;
   stop)
     stop
+    RETVAL=$?
     ;;
   status)
     checkstatus
+    RETVAL=$?
     ;;
   restart)
     restart
+    RETVAL=$?
     ;;
   condrestart|try-restart)
     condrestart
+    RETVAL=$?
     ;;
   *)
     echo $"Usage: $0 {start|stop|status|restart|try-restart|condrestart}"
